### ISSUE TITLE
bash demo

### ISSUE THREAD

**Issue by timchenxiaoyu** [yskszk63/ssssh#22]
use ssh client test

PTY allocation request failed on channel 0
shell request failed on channel 0

< NewKeys(NewKeys)
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: > NewKeys(NewKeys)
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < ServiceRequest(ServiceRequest { service_name: "ssh-userauth" })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: > ServiceAccept(ServiceAccept { service_name: "ssh-userauth" })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < UserauthRequest(UserauthRequest { user_name: "root", service_name: "ssh-connection", method: None })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: > UserauthSuccess(UserauthSuccess)
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < ChannelOpen(ChannelOpen { sender_channel: 0, initial_window_size: 1048576, maximum_packet_size: 16384, typ: Session(()) })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: > ChannelOpenConfirmation(ChannelOpenConfirmation { recipient_channel: 0, sender_channel: 0, initial_window_size: 1048576, maximum_packet_size: 16384, additional_data: b"" })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < ChannelRequest(ChannelRequest { recipient_channel: 0, want_reply: true, typ: PtyReq(PtyReq { term: "xterm-256color", width: 254, height: 63, width_px: 3556, height_px: 2142, modes: b"\x81\0\0\x96\0\x80\0\0\x96\0\x01\0\0\0\x03\x02\0\0\0\x1c\x03\0\0\0\x7f\x04\0\0\0\x15\x05\0\0\0\x04\x06\0\0\0\xff\x07\0\0\0\xff\x08\0\0\0\x11\t\0\0\0\x13\n\0\0\0\x1a\x0c\0\0\0\x12\r\0\0\0\x17\x0e\0\0\0\x16\x12\0\0\0\x0f\x1e\0\0\0\0\x1f\0\0\0\0 \0\0\0\0!\0\0\0\0\"\0\0\0\0#\0\0\0\0$\0\0\0\x01%\0\0\0\0&\0\0\0\x01'\0\0\0\x01(\0\0\0\0)\0\0\0\x01*\0\0\0\x012\0\0\0\x013\0\0\0\x014\0\0\0\05\0\0\0\x016\0\0\0\x017\0\0\0\x018\0\0\0\09\0\0\0\0:\0\0\0\0;\0\0\0\x01<\0\0\0\x01=\0\0\0\x01>\0\0\0\0F\0\0\0\x01G\0\0\0\0H\0\0\0\x01I\0\0\0\0J\0\0\0\0K\0\0\0\0Z\0\0\0\x01[\0\0\0\x01\\\0\0\0\0]\0\0\0\0\0" }) })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: > ChannelFailure(ChannelFailure { recipient_channel: 0 })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < ChannelRequest(ChannelRequest { recipient_channel: 0, want_reply: false, typ: Env(Env { name: "LANG", value: "zh_CN.UTF-8" }) })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: > ChannelFailure(ChannelFailure { recipient_channel: 0 })
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < ChannelRequest(ChannelRequest { recipient_channel: 0, want_reply: true, typ: Shell(()) })
DEBUG 2021-05-08T07:49:40Z: ssssh::connection::run: channel: 0, type: None output: SshOutput(PipeRead(14)) opened.
DEBUG 2021-05-08T07:49:40Z: ssssh::connection::run: channel: 0, type: Some(Stderr) output: SshOutput(PipeRead(16)) opened.
DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: > ChannelSuccess(ChannelSuccess { recipient_channel: 0 })
DEBUG 2021-05-08T07:49:40Z: ssssh::connection::run: spawn handler 0
DEBUG 2021-05-08T07:49:40Z: ssssh::connection::run: connection done.

**Comment by yskszk63** [comment]
Thank you for posting issue.

> DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < ChannelRequest(ChannelRequest { recipient_channel: 0, want_reply: true, typ: PtyReq(PtyReq { term:  ...

> DEBUG 2021-05-08T07:49:40Z: ssssh::stream::msg: < ChannelRequest(ChannelRequest { recipient_channel: 0, want_reply: false, typ: Env(Env { name: "LANG", ...

Sorry, following is not yet implemented.

- [Requesting a Pseudo-Terminal](https://tools.ietf.org/html/rfc4254#section-6.2)
- [Environment Variable Passing](https://tools.ietf.org/html/rfc4254#section-6.4)
- Many other...

Implementation [here](https://github.com/yskszk63/ssssh/blob/7c03a07719c42d12a2715422adefd86dc6a684e8/src/connection/run/on_channel_request.rs#L26)

**Comment by timchenxiaoyu** [comment]
if  Pseudo-Terminal  and Environment Variable Passing not Implement, does bash demo can not run currently ?

**Comment by yskszk63** [comment]
Run server (Simple echo server)

```
$ RUST_LOG=debug cargo run --example simple
```

Run Client

```
$ ssh -p2222 -F/dev/null ::1
The authenticity of host '[::1]:2222 ([::1]:2222)' can't be established.
ED25519 key fingerprint is SHA256:2xG5hi3DHcZnBn4wvqmYlfjtSRioqPbXEjfTnruEMG0.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[::1]:2222' (ED25519) to the list of known hosts.
PTY allocation request failed on channel 0
abc
abc
def
def
...
```

After run client.Please enter something quickly.Example `abc`. (Timeout is 5sec)

Please use `ssh -F/dev/null`. Because may be `/etc/ssh/ssh_config` or `~/.ssh/config` specify `SendEnv=xxx`.
May be ignore pty allocation failed by client.

> if here return ChannelSuccess. bash demo can work ?

I think it will work.

**Comment by timchenxiaoyu** [comment]
let status = Command::new("bash")
                                .stdin(stdin)
                                .stdout(stdout)
                                .stderr(stderr)
                                .status()
i think we need create tty/pty there

**Comment by yskszk63** [comment]
You are talking about this demo. understood. 
https://github.com/yskszk63/ssssh/blob/master/examples/bash.rs

I think it will work if implements "Environment Variable Passing". (Prompt does not come out)
If possible, I would like to make "Pseudo-Terminal" work as well.

**Comment by timchenxiaoyu** [comment]
tks, i will wait your implement and test again.

**Comment by timchenxiaoyu** [comment]
thank you very much，great ！ it work ！！！

**Comment by timchenxiaoyu** [comment]
btw，i try to implement tomorrow，but not work

`mod pipestream;

use nix::{pty, fcntl};
use nix::fcntl::{FcntlArg, FdFlag};
use std::os::unix::io::FromRawFd;
use log::{debug,warn};
use tokio::io::{copy, AsyncReadExt, AsyncWriteExt};

use std::os::unix::process::CommandExt as StdUnixCommandExt;
use crate::pipestream::PipeStream;
use nix::pty::OpenptyResult;
use std::process::Child;
use futures::{Sink, AsyncWrite};

#[tokio::main]
async fn main() {

    let pseudo = pty::openpty(None, None).unwrap();

    let _ = fcntl::fcntl(pseudo.master, FcntlArg::F_SETFD(FdFlag::FD_CLOEXEC))
        .map_err(|e| warn!("fnctl pseudo.master {:?}", e));
    let _ = fcntl::fcntl(pseudo.slave, FcntlArg::F_SETFD(FdFlag::FD_CLOEXEC))
        .map_err(|e| warn!("fcntl pseudo.slave {:?}", e));



    let mut child = std::process::Command::new("bash")
        .spawn_pty_async(&pseudo).unwrap();

    let stream = PipeStream::from_fd(pseudo.master);
    let (mut r,mut w) = tokio::io::split(stream);

    tokio_codec::FramedRead::new(r,tokio_codec::BytesCodec::new());


    tokio::spawn(async move{
        copy(&mut r,&mut tokio::io::stdout()).await;
    });

    tokio::spawn(async move{
        copy(&mut tokio::io::stdin(),&mut w).await;
    });

    child.wait();
}



pub trait CommandExt {
    fn spawn_pty_async(&mut self, pty: &OpenptyResult)-> std::io::Result<Child>  ;
}

impl CommandExt for std::process::Command {
    fn spawn_pty_async(&mut self, pty: &OpenptyResult) -> std::io::Result<Child> {

        let child_stdin = unsafe { std::process::Stdio::from_raw_fd(pty.slave) };
        let child_stdout = unsafe { std::process::Stdio::from_raw_fd(pty.slave) };
        let child_stderr = unsafe { std::process::Stdio::from_raw_fd(pty.slave) };

        let masterpty = pty.master;
        self.stdout(child_stdout);
        self.stdin(child_stdin);
        self.stderr(child_stderr);

        self.before_exec(move || {
            unsafe {
            if libc::close(masterpty) != 0 {
                return Err(std::io::Error::last_os_error());
            }

            if libc::setsid() < 0 {
                return Err(std::io::Error::last_os_error());
            }

            if libc::ioctl(0, libc::TIOCSCTTY.into(), 1) != 0 {
                return Err(std::io::Error::last_os_error());
            }
        }
            Ok(())
        });

        Ok(self.spawn().unwrap())
    }
}`

can not get  "[root@test tmp]#" first and display ls towice ,do you kown why ?

![image](https://user-images.githubusercontent.com/9782796/117907266-14cd2b80-b309-11eb-956e-49ecd10b281d.png)

**Comment by yskszk63** [comment]
Since the topic has deviated from this issue, I made a sample to gist.
https://gist.github.com/yskszk63/a806da0e35ca28abb2cbac5cdc4ca127

- I'm not sure, but rust's stdout is line buffered. So I think it's better not to use it.
- Set to raw mode to turn off the echo back function on the master side of pty.

Can you close this issue if it's okay?

**Comment by timchenxiaoyu** [comment]
ok
