### ISSUE TITLE
public key auth be called towice

### ISSUE THREAD

**Issue by timchenxiaoyu** [yskszk63/ssssh#26]
```
     handlers.on_auth_publickey(|username: String,algorithm: String, publickey: String| {
                    async move {
                        println!("{},{},{}",username,algorithm,publickey);
                        Ok(true)
                    }.boxed()
                });
```

![image](https://user-images.githubusercontent.com/9782796/118062046-ba939f80-b3c8-11eb-8d69-6fa5ba7f6eaf.png)

on_userauth_publickey_nosig  and  on_userauth_publickey_sig  all execute 

why ?

**Comment by yskszk63** [comment]
Currently, all of the following messages are dispatched to the same method.

- Confirmation message whether the public key is acceptable (without signature)
- Message signed by the client with the private key

(Specifications of [here](https://datatracker.ietf.org/doc/html/rfc4252#section-7))

Is it nice to have an argument to tell if the signature has been verified?

**Comment by timchenxiaoyu** [comment]
it is nice to have an argument to tell if the signature has been verified.

**Comment by yskszk63** [comment]
Sorry for the slow response.

It is divided into the following two methods according to whether it has been verified or not.

- [on_auth_publickey](https://yskszk63.github.io/ssssh/ssssh/struct.Handlers.html#method.on_auth_publickey)
- [on_auth_publickey_signature_verified_after_accepted](https://yskszk63.github.io/ssssh/ssssh/struct.Handlers.html#method.on_auth_publickey_signature_verified_after_accepted)
    - The default behavior if not specified is successful authentication if validation is successful and accepted by `on_auth_publickey`.

Please refer to the linked document for an example.

**Comment by timchenxiaoyu** [comment]
tks @yskszk63
