### ISSUE TITLE
public key not equal

### ISSUE THREAD

**Issue by timchenxiaoyu** [yskszk63/ssssh#27]
I want use  on_auth_publickey   verify    /root/.ssh/authorized_keys

but 

```
     handlers.on_auth_publickey(|username: String,algorithm: String, publickey: String| {

                   
```
above publickey is not equal to  local public key   /root/.ssh/authorized_keys

**Comment by yskszk63** [comment]
The following has been added.

- [authorized_keys parser](https://yskszk63.github.io/ssssh/ssssh/authorized_keys/struct.AuthorizedKeys.html)
- [Example](https://github.com/yskszk63/ssssh/blob/master/examples/publickey_auth.rs)

**Comment by timchenxiaoyu** [comment]
I have test ,it's ok, great ！
