### ISSUE TITLE
public key auth 

### ISSUE THREAD

**Issue by timchenxiaoyu** [yskszk63/ssssh#30]
when login use public key， both  on_userauth_publickey_nosig  and on_userauth_publickey_sig  be called ，why ？

**Comment by yskszk63** [comment]
@timchenxiaoyu 
May be your ssh client request twice.
1. Message whether the public key is acceptable <- no signature
2. Message signed with private key <- with signature

Please see here for more details.
https://datatracker.ietf.org/doc/html/rfc4252#section-7

**Comment by timchenxiaoyu** [comment]
I use  macos  built-in ssh cmd

**Comment by yskszk63** [comment]
>   Private keys are often stored in an encrypted form at the client host, and the user must supply a passphrase before the signature can be generated.  Even if they are not, the signing operation involves some expensive computation.  To avoid unnecessary processing and user interaction, the following message is provided for querying whether authentication using the "publickey" method would be acceptable.

- on_userauth_publickey_nosig ... No signature message that means `To avoid unnecessary processing and user interaction, the following message is provided for querying whether authentication using the "publickey" method would be acceptable.`
- on_userauth_publickey_sig ... Handle message contains Publickey and Signature. Computing signature is `the signing operation involves some expensive computation. `

Please see here for more details.
https://datatracker.ietf.org/doc/html/rfc4252#section-7

**Comment by timchenxiaoyu** [comment]
tks！
